Repository SSUMC-7th/Spring_Boot_D, pull requests merged in 2024-11, with the labels that each got.

#21 [Juni] Chapter 5. JPA 기초 및 프로젝트 구조
  .DS_Store
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  spring/.gitignore
  spring/.idea/gradle.xml
  spring/.idea/misc.xml
  spring/build.gradle
  spring/gradle/wrapper/gradle-wrapper.jar
  spring/gradle/wrapper/gradle-wrapper.properties
  spring/gradlew
  spring/gradlew.bat
  spring/settings.gradle
  spring/src/main/java/umc/spring/Application.java
  spring/src/main/resources/application.properties
  spring/src/main/resources/application.yml
  spring/src/test/java/umc/spring/ApplicationTests.java
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/.DS_Store
  src/main/java/umc/.DS_Store
  src/main/java/umc/study/.DS_Store
  src/main/java/umc/study/Application.java
  src/main/java/umc/study/domain/.DS_Store
  src/main/java/umc/study/domain/base/BaseEntity.java
  src/main/java/umc/study/domain/base/Score.java
  src/main/java/umc/study/domain/enums/AttachPhoto.java
  src/main/java/umc/study/domain/enums/Attainment_Mission.java
  src/main/java/umc/study/domain/enums/Favorite_Food.java
  src/main/java/umc/study/domain/enums/Gender.java
  src/main/java/umc/study/domain/enums/IsActive.java
  src/main/java/umc/study/domain/enums/IsSecession.java
  src/main/java/umc/study/domain/enums/Status.java
  src/main/java/umc/study/domain/enums/isCompleted.java
  src/main/java/umc/study/domain/mapping/Inquiry.java
  src/main/java/umc/study/domain/mapping/Mission.java
  src/main/java/umc/study/domain/mapping/Mission_point.java
  src/main/java/umc/study/domain/mapping/Region.java
  src/main/java/umc/study/domain/mapping/Restaurant.java
  src/main/java/umc/study/domain/mapping/Review.java
  src/main/java/umc/study/domain/mapping/Review_image.java
  src/main/java/umc/study/domain/mapping/User.java
  src/main/java/umc/study/domain/mapping/Usermission.java
  src/main/java/umc/study/web/.DS_Store
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/java/umc/spring/ApplicationTests.java
Labels: ✨ Chapter05

#24 [simba] Chapter6. JPA 활용
  build.gradle
  src/main/generated/umc/study/domain/QFoodCategory.java
  src/main/generated/umc/study/domain/QMember.java
  src/main/generated/umc/study/domain/QMission.java
  src/main/generated/umc/study/domain/QRegion.java
  src/main/generated/umc/study/domain/QReview.java
  src/main/generated/umc/study/domain/QStore.java
  src/main/generated/umc/study/domain/QTerms.java
  src/main/generated/umc/study/domain/base/QBaseEntity.java
  src/main/generated/umc/study/domain/mapping/QMemberAgree.java
  src/main/generated/umc/study/domain/mapping/QMemberMission.java
  src/main/generated/umc/study/domain/mapping/QMemberPrefer.java
  src/main/java/umc/study/Application.java
  src/main/java/umc/study/config/QueryDSLConfig.java
  src/main/java/umc/study/domain/Store.java
  src/main/java/umc/study/repository/StoreRepository/StoreRepository.java
  src/main/java/umc/study/repository/StoreRepository/StoreRepositoryCustom.java
  src/main/java/umc/study/repository/StoreRepository/StoreRepositoryImpl.java
  src/main/java/umc/study/service/StoreService/StoreQueryService.java
  src/main/java/umc/study/service/StoreService/StoreQueryServiceImpl.java
  src/main/resources/application.yml
Labels: ✨ Chapter06

#28 [Stitch] Chapter6. JPA 활용
  build.gradle
  src/main/generated/umc/spring/domain/QFoodCategory.java
  src/main/generated/umc/spring/domain/QMember.java
  src/main/generated/umc/spring/domain/QMission.java
  src/main/generated/umc/spring/domain/QRegion.java
  src/main/generated/umc/spring/domain/QReview.java
  src/main/generated/umc/spring/domain/QStore.java
  src/main/generated/umc/spring/domain/QTerms.java
  src/main/generated/umc/spring/domain/common/QBaseEntity.java
  src/main/generated/umc/spring/domain/mapping/QMemberAgree.java
  src/main/generated/umc/spring/domain/mapping/QMemberMission.java
  src/main/generated/umc/spring/domain/mapping/QMemberPrefer.java
  src/main/java/umc/spring/Application.java
  src/main/java/umc/spring/config/QueryDSLConfig.java
  src/main/java/umc/spring/domain/Review.java
  src/main/java/umc/spring/domain/Store.java
  src/main/java/umc/spring/service/StoreRepository.java
  src/main/java/umc/spring/service/StoreRepositoryCustom.java
  src/main/java/umc/spring/service/StoreRepositoryImpl.java
  src/main/java/umc/spring/service/StoreService/StoreQueryService.java
  src/main/java/umc/spring/service/StoreService/StoreQueryServiceImpl.java
Labels: ✨ Chapter06

#36 [Stitch] Chapter 7. API 응답 통일 & 에러 핸들러
  build.gradle
  src/main/java/umc/spring/apiPayload/ApiResponse.java
  src/main/java/umc/spring/apiPayload/code/BaseCode.java
  src/main/java/umc/spring/apiPayload/code/BaseErrorCode.java
  src/main/java/umc/spring/apiPayload/code/ErrorReasonDTO.java
  src/main/java/umc/spring/apiPayload/code/ReasonDTO.java
  src/main/java/umc/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/spring/apiPayload/code/status/SuccessStatus.java
  src/main/java/umc/spring/apiPayload/exception/ExceptionAdvice.java
  src/main/java/umc/spring/apiPayload/exception/GeneralException.java
  src/main/java/umc/spring/apiPayload/exception/handler/TempHandler.java
  src/main/java/umc/spring/service/TempService/TempCommandQueryImpl.java
  src/main/java/umc/spring/service/TempService/TempCommandService.java
  src/main/java/umc/spring/service/TempService/TempQueryService.java
  src/main/java/umc/spring/service/TempService/TempQueryServiceImpl.java
  src/main/java/umc/spring/web/controller/TempConverter.java
  src/main/java/umc/spring/web/controller/TempRestController.java
  src/main/java/umc/spring/web/dto/TempResponse.java
  src/main/java/umc/spring/web/dto/TempResquest.java
Labels: ✨ Chapter07

#35 [simba] Chapter 7. API 응답 통일 & 에러 핸들러
  build.gradle
  src/main/java/umc/study/ApiPayload/ApiResponse.java
  src/main/java/umc/study/ApiPayload/code/BaseCode.java
  src/main/java/umc/study/ApiPayload/code/BaseErrorCode.java
  src/main/java/umc/study/ApiPayload/code/ErrorReasonDTO.java
  src/main/java/umc/study/ApiPayload/code/ReasonDTO.java
  src/main/java/umc/study/ApiPayload/code/status/ErrorStatus.java
  src/main/java/umc/study/ApiPayload/code/status/SuccessStatus.java
  src/main/java/umc/study/ApiPayload/exception/ExceptionAdvice.java
  src/main/java/umc/study/ApiPayload/exception/GeneralException.java
  src/main/java/umc/study/ApiPayload/exception/handler/TempHandler.java
  src/main/java/umc/study/converter/TempConverter.java
  src/main/java/umc/study/service/TempService/TempCommandService.java
  src/main/java/umc/study/service/TempService/TempCommandServiceImpl.java
  src/main/java/umc/study/service/TempService/TempQueryService.java
  src/main/java/umc/study/service/TempService/TempQueryServiceImpl.java
  src/main/java/umc/study/web/controller/TempRestController.java
  src/main/java/umc/study/web/dto/TempRequest.java
  src/main/java/umc/study/web/dto/TempResponse.java
Labels: ✨ Chapter07

#57 [Simba] Chapter 8. API & Swagger & Annotation # 1
  build.gradle
  src/main/java/umc/study/ApiPayload/code/status/ErrorStatus.java
  src/main/java/umc/study/ApiPayload/exception/handler/FoodCategoryHandler.java
  src/main/java/umc/study/config/SwaggerConfig.java
  src/main/java/umc/study/converter/MemberConverter.java
  src/main/java/umc/study/converter/MemberPreferConverter.java
  src/main/java/umc/study/domain/Member.java
  src/main/java/umc/study/domain/mapping/MemberPrefer.java
  src/main/java/umc/study/repository/FoodCategoryRepository/FoodCategoryRepository.java
  src/main/java/umc/study/repository/MemberRepository/MemberRepository.java
  src/main/java/umc/study/service/MemberService/MemberCommandService.java
  src/main/java/umc/study/service/MemberService/MemberCommandServiceImpl.java
  src/main/java/umc/study/service/MemberService/MemberQueryService.java
  src/main/java/umc/study/service/MemberService/MemberQueryServiceImpl.java
  src/main/java/umc/study/validation/annotation/ExistCategories.java
  src/main/java/umc/study/validation/validator/CategoriesExistValidator.java
  src/main/java/umc/study/web/controller/MemberRestController.java
  src/main/java/umc/study/web/dto/MemberRequestDTO.java
  src/main/java/umc/study/web/dto/MemberResponseDTO.java
  src/main/resources/application.yml
Labels: ✨ Chapter08

#68 [Simba] Chapter 8. API & Swagger & Annotation issue #2,4
  src/main/generated/umc/study/domain/QReview.java
  src/main/java/umc/study/converter/MissionConverter.java
  src/main/java/umc/study/converter/ReviewConverter.java
  src/main/java/umc/study/domain/Review.java
  src/main/java/umc/study/repository/MissionRepository/MissionRepository.java
  src/main/java/umc/study/repository/ReviewRepository/ReviewRepository.java
  src/main/java/umc/study/service/MissionService/MissionCommandService.java
  src/main/java/umc/study/service/MissionService/MissionCommandServiceImpl.java
  src/main/java/umc/study/service/MissionService/MissionQueryService.java
  src/main/java/umc/study/service/MissionService/MissionQueryServiceImpl.java
  src/main/java/umc/study/service/ReviewService/ReviewCommandService.java
  src/main/java/umc/study/service/ReviewService/ReviewCommandServiceImpl.java
  src/main/java/umc/study/service/ReviewService/ReviewQueryService.java
  src/main/java/umc/study/service/ReviewService/ReviewQueryServiceImpl.java
  src/main/java/umc/study/web/controller/MissionRestController.java
  src/main/java/umc/study/web/controller/ReviewRestController.java
  src/main/java/umc/study/web/dto/MissionRequestDTO.java
  src/main/java/umc/study/web/dto/MissionResponseDTO.java
  src/main/java/umc/study/web/dto/ReviewRequestDTO.java
  src/main/java/umc/study/web/dto/ReviewResponseDTO.java
Labels: ✨ Chapter08

#72 [Stitch] Chapter 8. API & Swagger & Annotation issue #2
  src/main/java/umc/spring/apiPayload/exception/handler/UserHandler.java
  src/main/java/umc/spring/converter/ReviewConverter.java
  src/main/java/umc/spring/domain/Review.java
  src/main/java/umc/spring/repository/ReviewRepository/ReviewRepository.java
  src/main/java/umc/spring/service/ReviewService/ReviewCommandService.java
  src/main/java/umc/spring/service/ReviewService/ReviewCommandServiceImpl.java
  src/main/java/umc/spring/service/ReviewService/ReviewQueryService.java
  src/main/java/umc/spring/service/ReviewService/ReviewQueryServiceImpl.java
  src/main/java/umc/spring/validation/annotation/ExistUser.java
  src/main/java/umc/spring/validation/validator/UserExistValidator.java
  src/main/java/umc/spring/web/controller/ReviewController.java
  src/main/java/umc/spring/web/dto/MemberRequestDTO.java
  src/main/java/umc/spring/web/dto/ReviewRequestDTO.java
  src/main/java/umc/spring/web/dto/ReviewResponseDTO.java
Labels: ✨ Chapter08
